server:
  port: ${SERVER_PORT}

database:
  url: ${DB_URL}
  user: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver: org.postgresql.Driver

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true
  ddl-auto: update

entity:
  path: com.example.meetup

